# Generated by Django 3.1.3 on 2021-01-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rwandan_franc', models.DecimalField(db_index=True, decimal_places=10, max_digits=19)),
                ('congolese_franc', models.DecimalField(db_index=True, decimal_places=10, max_digits=19)),
                ('Usd', models.DecimalField(db_index=True, decimal_places=10, max_digits=19)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
