# Generated by Django 3.1.3 on 2021-01-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='Rwandan_franc',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='rate',
            name='Usd',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='rate',
            name='congolese_franc',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=19),
        ),
    ]
