# Generated by Django 3.1.3 on 2020-11-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='contactu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(db_index=True, max_length=500)),
                ('email', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(db_index=True, max_length=200)),
                ('customer_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('customer_email', models.CharField(db_index=True, max_length=200)),
                ('customer_phon', models.CharField(db_index=True, max_length=200)),
                ('customer_dob', models.CharField(db_index=True, max_length=200)),
                ('customer_sex', models.CharField(db_index=True, max_length=200)),
                ('customer_notionality', models.CharField(db_index=True, max_length=200)),
                ('customer_ocupation', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('Employee_email', models.CharField(db_index=True, max_length=200)),
                ('Employee_phon', models.CharField(db_index=True, max_length=200)),
                ('Employee_name', models.CharField(db_index=True, max_length=200)),
                ('Employee_dob', models.CharField(db_index=True, max_length=200)),
                ('Employee_sex', models.CharField(db_index=True, max_length=200)),
                ('Employee_function', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_type', models.CharField(db_index=True, max_length=200)),
                ('landlord_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('landlord_name', models.CharField(db_index=True, max_length=200)),
                ('landlord_phone', models.CharField(db_index=True, max_length=200)),
                ('landlord_email', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Propertie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_description', models.TextField(blank=True, db_index=True, max_length=500)),
                ('Bedroom', models.IntegerField(db_index=True)),
                ('Bathroom', models.IntegerField(db_index=True)),
                ('Property_image', models.ImageField(blank=True, upload_to='properties/')),
                ('available', models.BooleanField(default=True)),
                ('vaccant', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_username', models.CharField(db_index=True, max_length=50)),
                ('U_Userpassword', models.CharField(db_index=True, max_length=50, unique=True)),
                ('U_email', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Property_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='properties/')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropertyId', to='rental.propertie')),
            ],
        ),
        migrations.AddField(
            model_name='propertie',
            name='Advert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='rental.type'),
        ),
        migrations.AddField(
            model_name='propertie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='rental.category'),
        ),
        migrations.AddField(
            model_name='propertie',
            name='landlord_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to='rental.landlord'),
        ),
        migrations.CreateModel(
            name='BookedPropertie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('vaccant', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Booker', to='rental.customer')),
                ('property_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advert', to='rental.propertie')),
            ],
        ),
    ]
