# Generated by Django 3.1.3 on 2021-01-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedPropertie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(db_index=True, max_length=100)),
                ('customer_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('customer_name', models.CharField(db_index=True, max_length=100)),
                ('customer_email', models.EmailField(db_index=True, max_length=100)),
                ('customer_phon', models.CharField(db_index=True, max_length=100)),
                ('booking_period', models.CharField(db_index=True, max_length=100)),
                ('property_booked', models.CharField(db_index=True, max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('vaccant', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='contactu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(db_index=True, max_length=500, null=True)),
                ('email', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('Employee_email', models.CharField(db_index=True, max_length=200)),
                ('Employee_phon', models.CharField(db_index=True, max_length=200)),
                ('Employee_name', models.CharField(db_index=True, max_length=200)),
                ('Employee_dob', models.DateField(blank=True, db_index=True, max_length=200, null=True)),
                ('Employee_sex', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('Employee_function', models.CharField(blank=True, db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Employee',
                'ordering': ('Employee_id',),
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_type', models.CharField(db_index=True, max_length=200)),
                ('landlord_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('landlord_name', models.CharField(db_index=True, max_length=200)),
                ('landlord_phone', models.CharField(db_index=True, max_length=200)),
                ('landlord_email', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Landlord',
                'ordering': ('landlord_id',),
            },
        ),
        migrations.CreateModel(
            name='Propertie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advert_type', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('payable', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('Bedroom', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Bathroom', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('cell', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, upload_to='properties/%Y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('vaccant', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='rental.category')),
                ('landlord_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to='rental.landlord')),
            ],
            options={
                'verbose_name': 'Propertie',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_name', models.CharField(db_index=True, max_length=50)),
                ('U_username', models.CharField(db_index=True, max_length=50)),
                ('U_Userpassword', models.CharField(db_index=True, max_length=50, unique=True)),
                ('U_email', models.CharField(db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(db_index=True, max_length=100)),
                ('customer_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('customer_name', models.CharField(db_index=True, max_length=100)),
                ('customer_email', models.EmailField(db_index=True, max_length=100)),
                ('customer_phon', models.CharField(db_index=True, max_length=100)),
                ('customer_dob', models.DateField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_sex', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_notionality', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_ocupation', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('Date_taken', models.DateField(blank=True, db_index=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property_taken_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='rental.propertie')),
            ],
            options={
                'verbose_name': 'Property_Taken',
                'ordering': ('customer_id',),
            },
        ),
        migrations.CreateModel(
            name='Property_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropertyId', to='rental.propertie')),
            ],
        ),
    ]
