# Generated by Django 3.1.3 on 2021-01-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedpropertie',
            name='customer_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookedpropertie',
            name='property_booked',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
