# Generated by Django 3.1.3 on 2020-12-04 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('customer_id',), 'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('Employee_id',), 'verbose_name': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='landlord',
            options={'ordering': ('landlord_id',), 'verbose_name': 'Landlord'},
        ),
        migrations.AlterModelOptions(
            name='propertie',
            options={'ordering': ('-created',), 'verbose_name': 'Propertie'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('name',), 'verbose_name': 'Type'},
        ),
        migrations.AddField(
            model_name='propertie',
            name='cell',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertie',
            name='name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertie',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertie',
            name='sector',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertie',
            name='village',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactu',
            name='message',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_dob',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_notionality',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_ocupation',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_sex',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_dob',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_function',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_sex',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='Bathroom',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='Bedroom',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='Property_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='property_description',
            field=models.TextField(blank=True, db_index=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='U_email',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='propertie',
            index_together={('id', 'slug')},
        ),
    ]
