# Generated by Django 3.1.3 on 2021-01-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20210104_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedpropertie',
            name='property_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Property_booked', to='rental.propertie'),
        ),
    ]
