# Generated by Django 3.1.3 on 2020-12-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20201204_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertie',
            name='Property_image',
            field=models.ImageField(blank=True, upload_to='properties/%Y/%m/%d'),
        ),
    ]
