# Generated by Django 3.1.3 on 2021-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20210106_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertie',
            name='image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
