# Generated by Django 3.1.3 on 2020-12-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20201204_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertie',
            old_name='property_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='propertie',
            old_name='Property_image',
            new_name='image',
        ),
    ]
