# Generated by Django 3.1.3 on 2020-12-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_auto_20201204_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='currency',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertie',
            name='payable',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
