# Generated by Django 3.1.3 on 2020-12-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_auto_20201209_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertie',
            name='property_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
