# Generated by Django 3.1.3 on 2020-12-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_auto_20201209_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertie',
            name='currency',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='payable',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
