# Generated by Django 3.1.3 on 2020-12-16 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_auto_20201209_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(db_index=True, max_length=100)),
                ('customer_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('customer_name', models.CharField(db_index=True, max_length=100)),
                ('customer_email', models.EmailField(db_index=True, max_length=100)),
                ('customer_phon', models.CharField(db_index=True, max_length=100)),
                ('customer_dob', models.DateField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_sex', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_notionality', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_ocupation', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('Date_taken', models.DateField(blank=True, db_index=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property_taken_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Identity', to='rental.propertie')),
            ],
            options={
                'verbose_name': 'Property_Taken',
                'ordering': ('customer_id',),
            },
        ),
        migrations.RemoveField(
            model_name='bookedpropertie',
            name='customer_booker',
        ),
        migrations.AddField(
            model_name='bookedpropertie',
            name='booking_period',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedpropertie',
            name='customer_email',
            field=models.EmailField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedpropertie',
            name='customer_id',
            field=models.CharField(db_index=True, default=32323, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedpropertie',
            name='customer_name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedpropertie',
            name='customer_phon',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedpropertie',
            name='customer_type',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='U_name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
