# Generated by Django 3.1.3 on 2020-12-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_auto_20201216_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertie',
            name='Advert_type',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property_taken',
            name='property_taken_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='rental.propertie'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
