# Generated by Django 3.1.3 on 2020-12-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_auto_20201221_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertie',
            name='Advert_type',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
