# Generated by Django 3.1.3 on 2020-12-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_auto_20201221_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
